# Generated by Django 6.0.3 on 2026-03-18 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cibo', models.TextField()),
                ('situazione', models.TimeField()),
                ('sensazione', models.CharField(max_length=150)),
            ],
        ),
    ]
