# Generated by Django 6.0.3 on 2026-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_alimentare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasto',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
