# Generated by Django 6.0.3 on 2026-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_alimentare', '0002_pasto_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasto',
            name='situazione',
            field=models.CharField(max_length=100),
        ),
    ]
