# Generated by Django 6.0.3 on 2026-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_alimentare', '0003_alter_pasto_situazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasto',
            old_name='situazione',
            new_name='conChi',
        ),
        migrations.AddField(
            model_name='pasto',
            name='come_sento_dopo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pasto',
            name='come_sento_prima',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pasto',
            name='luogo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pasto',
            name='cibo',
            field=models.TextField(default=''),
        ),
    ]
