# Generated by Django 6.0.3 on 2026-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_alimentare', '0004_rename_situazione_pasto_conchi_pasto_come_sento_dopo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasto',
            name='sensazione',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
